### ISSUE TITLE
Description needs updating

### ISSUE THREAD

**Issue by kuzeko** [BONSAMURAIS/ontology#11]
https://github.com/BONSAMURAIS/ontology/blob/4f62d926c03653bc1bcf5a7872b65f94211d6adb/core/ontology_v0.1.ttl#L36-L38

**Comment by tngTUDOR** [comment]
@kuzeko , the new version has a slightly better rdfs:comment:

```
                based on changes discussed on Jan2020!

```

Is this enough to close this issue, or are you expecting something more?

**Comment by kuzeko** [comment]
Sure! :)
