### ISSUE TITLE
Set up automatic tests of ttl and rdf/xml files

### ISSUE THREAD

**Issue by kuzeko** [BONSAMURAIS/ontology#7]
We should probably have a CI environment/workflow in place as @tngTUDOR  suggests.

> apparently, the command-line `riot` is easy to use with docker
so I was thinking we could add a "test" step in the ontology CD pipeline to verify before deploying

> for example:

```
docker run -it --rm -v `pwd`:/rdf stain/jena riot -v --debug --validate --time ontology_v0.1.ttl

ontology_v0.1.ttl :  0.07 sec : 81 Triples : 1,208.96 per second
```

**Comment by tngTUDOR** [comment]
I can see how to implement this as a job part of the test stage in travis, but for the moment, the `filename` of the file(s) to test are static.
@kuzeko any hints on which files to test ? 

- [ ] core/*.ttl
- [ ] core/*.rdf

**Comment by tngTUDOR** [comment]
this is in progress. see branch issue-7

**Comment by kuzeko** [comment]
It should be that the `*.ttl` files are isomorphic to the `*.rdf` files.
I think that `{*.ttl,*.rdf}` covers all extensions

**Comment by tngTUDOR** [comment]
branch with a solution to this was issue-7 and it was just merged.
